### ISSUE TITLE
A question about the application of LVGL combined with opengl

### ISSUE THREAD

**Issue by Yangyuanxin** [littlevgl/lv_lib_tinygl#2]
I have a requirement now that I hope lvgl and opengl can be used in combination with each other. Therefore, when using opengl, the device needs to have graphics card requirements. However, I saw the lv_tinygl demo you developed. Does it have to have a hardware GPU to run? ?

**Comment by Yangyuanxin** [comment]
In the future, is it possible for lvgl to support opengl? Because 3D display can be carried on a lightweight GUI, in this case, I hope to use the advantages of LVGL to operate 3D models to achieve my product requirements, and at the same time, it can also greatly reduce my resources.

**Comment by kisvegabor** [comment]
The experiments with TinyGL stopped here due to some issues in TinyGL or with it's integration. :slightly_frowning_face: 

Anyway, the OpenGL support can be added independently of LVGL. The "bridge" can be a buffer in which the rendered image is stored and LVGL display's it as an `lv_img`.
